#!/usr/bin/env bash
# Extract a variation overlay from a working copy of the baseline.
#
#   tooling/variations/extract.sh <variation> <workdir>
#
# <workdir> is a git clone of this baseline in which the variation was
# developed (in BASELINE naming — rebrand happens at materialize time). Every
# file added or modified relative to the clone's HEAD becomes
# `variations/<variation>/overlay/<path>`; deletions are recorded in
# `variations/<variation>/delete.txt`.
set -euo pipefail

name="${1:?variation name}"
work="${2:?working copy}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
baseline="$(cd "$here/../.." && pwd)"
vdir="$baseline/variations/$name"
mkdir -p "$vdir"

cd "$work"
git add -A -N .
# pnpm-lock.yaml is regenerated by materialize (new workspace packages change
# it); carrying a 400KB copy per variation would only add diff noise.
changed="$(git diff --name-only --diff-filter=AMRT HEAD | grep -v "^pnpm-lock.yaml$" || true)"
deleted="$(git diff --name-only --diff-filter=D HEAD)"

rm -rf "$vdir/overlay"
mkdir -p "$vdir/overlay"
n=0
while IFS= read -r f; do
  [ -z "$f" ] && continue
  mkdir -p "$vdir/overlay/$(dirname "$f")"
  cp "$f" "$vdir/overlay/$f"
  n=$((n+1))
done <<< "$changed"
if [ -n "$deleted" ]; then
  printf '%s\n' "$deleted" > "$vdir/delete.txt"
else
  rm -f "$vdir/delete.txt"
fi
echo "extract: $n file(s) → variations/$name/overlay$([ -n "$deleted" ] && echo ", $(printf '%s\n' "$deleted" | wc -l) deletion(s)")"
